Make async support
kiriharu/fish_text_ru pull request #5
Opened 2022-08-17 15:30 UTC by LulzLoL231

Добавил поддержку async протокола, написал пример использования (`examples/async_json_example.py`), добавил пояснения в README и поднял версию.

2022-08-25 09:14 UTC, kiriharu requested changes

2022-08-25 09:14 UTC, kiriharu commented on examples/async_json_example.py
> +titles = loop.run_until_complete(api.get(10))
В 3.8 можно использовать `asyncio.run()`

2022-08-25 09:14 UTC, kiriharu commented on pyproject.toml
> +httpx = "^0.23.0"
Асинхронный метод (и собственно установку httpx), пожалуйста, сделайте опциональным. Чтобы при установке можно было добавить поддержку асинхронности, она не всем нужна.
https://python-poetry.org/docs/pyproject/#extras

2022-08-25 12:34 UTC, LulzLoL231 commented on examples/async_json_example.py
> +titles = loop.run_until_complete(api.get(10))
Здесь специально используется `get_event_loop`, так как в случае с `asyncio.run` event loop сразу закрывается, тогда не  async сессия httpx не может закрыться правильно. Поэтому и использовал `get_event_loop`.

2022-08-25 12:45 UTC, LulzLoL231 commented on pyproject.toml
> +httpx = "^0.23.0"
Сделал httpx опциональным и поставил предупреждение в случае отсутствия httpx.

2022-09-03 21:05 UTC, merged

2022-09-03 21:05 UTC, kiriharu commented
Спасибо за вклад!